# Generated by Django 4.1.3 on 2022-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='followerCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='followingCount',
            field=models.IntegerField(),
        ),
    ]
