# Generated by Django 4.1.3 on 2022-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0002_alter_users_followercount_alter_users_followingcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tweet_ID', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='userID',
        ),
        migrations.AlterField(
            model_name='users',
            name='ProfileBackgroundIMG',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='ProfileIMG',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='followerCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='followingCount',
            field=models.IntegerField(blank=True),
        ),
    ]
