# Generated by Django 4.1.3 on 2022-11-21 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0003_posts_remove_users_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('DOB', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('followingCount', models.IntegerField(blank=True)),
                ('followerCount', models.IntegerField(blank=True)),
                ('followerList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('followingList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('ProfileIMG', models.CharField(max_length=128)),
                ('ProfileBackgroundIMG', models.CharField(max_length=128)),
                ('isUser', models.BooleanField(default=False)),
                ('followingStatus', models.BooleanField(default=False)),
                ('followRequestSent', models.BooleanField(default=False)),
                ('likedPosts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('Tweets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('Comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
