# Generated by Django 4.1.3 on 2022-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0004_user_rename_posts_post_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ProfileBackgroundIMG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ProfileIMG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Tweets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followRequestSent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followerCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followerList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingStatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
    ]
