# Generated by Django 4.1.3 on 2022-11-21 19:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0005_remove_user_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followerList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='Null', max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='followingList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='Null', max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
