# Generated by Django 4.1.3 on 2022-11-21 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0006_user_followerlist_user_followinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followerList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='followingList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
