# Generated by Django 4.1.3 on 2022-11-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0008_user_comments_user_profilebackgroundimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followerCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followingCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
