# Generated by Django 4.1.3 on 2022-11-21 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0009_user_followercount_user_followingcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followerCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingCount',
        ),
        migrations.AddField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 20, 45, 58, 317907)),
        ),
    ]
