# Generated by Django 4.1.3 on 2022-11-21 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0012_user_followercount_alter_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followRequestSent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='followingStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isUser',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 20, 48, 5, 178112)),
        ),
    ]
