# Generated by Django 4.1.3 on 2022-11-21 20:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0013_user_followrequestsent_user_followingstatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 20, 58, 6, 656176)),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='followerList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='followingList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, null=True, size=None),
        ),
    ]
