# Generated by Django 4.1.3 on 2022-11-21 20:58

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0014_delete_post_alter_user_date_alter_user_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerID', models.CharField(max_length=128)),
                ('Text', models.CharField(max_length=128)),
                ('Likes', models.IntegerField(blank=True, default=0)),
                ('LikedUsers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('URL', models.CharField(max_length=128)),
                ('ImageURL', models.CharField(max_length=128)),
                ('Comments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 20, 58, 18, 349209)),
        ),
    ]
