# Generated by Django 4.1.3 on 2022-11-21 21:03

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0015_post_alter_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.CharField(max_length=128)),
                ('OwnerID', models.CharField(max_length=128)),
                ('Text', models.CharField(max_length=128)),
                ('ImageURL', models.CharField(blank=True, max_length=128)),
                ('Likes', models.IntegerField(blank=True, default=0)),
                ('LikedUsers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('Replies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('Date', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 3, 16, 294946))),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 3, 16, 294666)),
        ),
        migrations.AlterField(
            model_name='post',
            name='ImageURL',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='URL',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 3, 16, 294337)),
        ),
    ]
