# Generated by Django 4.1.3 on 2022-11-21 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0017_alter_comment_date_alter_post_date_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 20, 0, 693905)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 20, 0, 693642)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2022, 11, 21, 21, 20, 0, 693353)),
        ),
    ]
