# Generated by Django 4.1.3 on 2022-11-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0020_alter_comment_date_alter_post_date_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='twittertestapi.user'),
        ),
    ]
