# Generated by Django 4.1.3 on 2022-11-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0021_alter_post_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='twittertestapi.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='PostID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='twittertestapi.post'),
        ),
    ]
