# Generated by Django 4.1.3 on 2022-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0023_remove_user_followerlist_user_followerlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followerList',
            field=models.ManyToManyField(blank=True, null=True, to='twittertestapi.user'),
        ),
    ]
