# Generated by Django 4.1.3 on 2022-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0024_alter_user_followerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followerCount',
        ),
        migrations.AddField(
            model_name='user',
            name='followerCount',
            field=models.ManyToManyField(blank=True, null=True, to='twittertestapi.user'),
        ),
    ]
