# Generated by Django 4.1.3 on 2022-11-22 16:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0026_alter_post_ownerid_remove_user_followercount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='twittertestapi.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
        migrations.AddField(
            model_name='user',
            name='likedPosts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
