# Generated by Django 4.1.3 on 2022-11-22 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twittertestapi', '0027_alter_post_ownerid_remove_user_likedposts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
        migrations.AddField(
            model_name='user',
            name='likedPosts',
            field=models.ManyToManyField(blank=True, null=True, to='twittertestapi.post'),
        ),
    ]
