# Generated by Django 4.1.3 on 2022-11-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0029_alter_user_followerlist_alter_user_followinglist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Tweets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
        migrations.AlterField(
            model_name='post',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='twittertestapi.user'),
        ),
    ]
