# Generated by Django 4.1.3 on 2022-11-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0030_remove_user_comments_remove_user_tweets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testing', models.ManyToManyField(blank=True, to='twittertestapi.post')),
            ],
        ),
    ]
