# Generated by Django 4.1.3 on 2022-11-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0031_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
