# Generated by Django 4.1.3 on 2022-11-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0034_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likedPosts',
            field=models.ManyToManyField(blank=True, to='twittertestapi.post'),
        ),
    ]
