# Generated by Django 4.1.3 on 2022-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0035_user_likedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Tweets',
            field=models.ManyToManyField(blank=True, related_name='Tweets', to='twittertestapi.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='likedPosts',
            field=models.ManyToManyField(blank=True, related_name='likedTweets', to='twittertestapi.post'),
        ),
    ]
