# Generated by Django 4.1.3 on 2022-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0036_user_tweets_alter_user_likedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Comments',
            field=models.ManyToManyField(blank=True, related_name='post', to='twittertestapi.post'),
        ),
    ]
