# Generated by Django 4.1.3 on 2022-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0037_user_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Replies',
        ),
        migrations.AddField(
            model_name='comment',
            name='Replies',
            field=models.ManyToManyField(blank=True, to='twittertestapi.comment'),
        ),
    ]
