# Generated by Django 4.1.3 on 2022-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0038_remove_comment_replies_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='LikedUsers',
        ),
        migrations.AddField(
            model_name='post',
            name='Comments',
            field=models.ManyToManyField(blank=True, related_name='comment', to='twittertestapi.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='LikedUsers',
            field=models.ManyToManyField(blank=True, related_name='likedUsers', to='twittertestapi.user'),
        ),
    ]
