# Generated by Django 4.1.3 on 2022-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0039_remove_post_comments_remove_post_likedusers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='LikedUsers',
        ),
        migrations.AddField(
            model_name='comment',
            name='LikedUsers',
            field=models.ManyToManyField(blank=True, related_name='likedCommentUsers', to='twittertestapi.user'),
        ),
    ]
