# Generated by Django 4.1.3 on 2022-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0041_alter_comment_ownerid_alter_comment_postid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Replies',
            new_name='Comments',
        ),
    ]
