# Generated by Django 4.1.3 on 2022-11-22 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0042_rename_replies_comment_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followRequestSent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followerCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingStatus',
        ),
    ]
