# Generated by Django 4.1.3 on 2022-11-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twittertestapi', '0044_remove_user_isuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Tweets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followerList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followingList',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ImageURL',
        ),
        migrations.RemoveField(
            model_name='post',
            name='LikedUsers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='OwnerID',
        ),
        migrations.RemoveField(
            model_name='post',
            name='URL',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
