# Generated by Django 4.1.3 on 2022-11-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittertestapi', '0046_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
