# Generated by Django 4.1.3 on 2022-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Text',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
