# Generated by Django 4.1.3 on 2022-11-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
    ]
