# Generated by Django 4.1.3 on 2022-11-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi', '0005_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Text', max_length=128),
        ),
    ]
